### ISSUE TITLE
Few questions with paper

### ISSUE THREAD

**Issue by ima9ine** [arpitbansal297/Universal-Guided-Diffusion#1]
Hi just read your paper and enjoyed cool idea to rescue classifier-guidance. 

Have you ever tried multiple guidance and wonder does it work well.  
(Like Segmentation + Style or Target location + Target Identity)
And I'm also curious about time/result comparison for sampling in Stable diffusion for various step.
Thanks!

**Comment by arpitbansal297** [comment]
Hi, thanks for showing interest in our paper. We have not conducted experiments with multiple guidances extensively but I would like to point you to figure 10 in which we have multiple guidances at work at the same time. They are inpainting, classifier, and segmentation guidances altogether.

Thanks
