### ISSUE TITLE
About Inference Time

### ISSUE THREAD

**Issue by nmakes** [arpitbansal297/Universal-Guided-Diffusion#13]
Hi,

Thanks so much for the great work and the code release. Quick question - what is the expected inference time for a single image (say, for the style transfer based guidance)? For me, a single image takes about 20 minutes using the [style_transfer.py](https://github.com/arpitbansal297/Universal-Guided-Diffusion/blob/main/stable-diffusion-guided/scripts/style_transfer.py) script - is this expected?

Also, I'm curious to know if there is a way to infer using lesser number of diffusion steps (e.g. 50)?

Thanks!

**Comment by AlexMaOLS** [comment]
Hi, would you mind sharing your device info? It takes me a around an hour to generate a clip guided image, I am running on a single V100 machine.

**Comment by arpitbansal297** [comment]
Hi,
At present, the question of how one can do universal guidance using a lesser number of steps is the open research question. The current work requires 500 steps and multiple self recurrences making it expensive.
