### ISSUE TITLE
Question regarding the guidance gradient.

### ISSUE THREAD

**Issue by pengzhangzhi** [arpitbansal297/Universal-Guided-Diffusion#5]
You take the gradient of loss v.r.t x_t, i.e., grad = d(loss)/ d(x_t), and update the predicted noise using the gradient, i.e., x_eps = x_eps - grad. If you want to update the noise why do you directly take the gradient w.r.t to x_eps? Is there are any special reasons?

**Comment by D0miH** [comment]
Yes, I have the same question. Did you find out why this is the case?

**Comment by arpitbansal297** [comment]
x_eps is the scaled gradient for x_t from the score based model perspective. Hence at the end we are mixing different gradients, x_eps takes one to the image manifold and the other grads enables image generation conditional on a certain constraint like segmentation map, object location etc.
